### ISSUE TITLE
Update zeppelin image

### ISSUE THREAD

**Issue by nachocab** [newfront/spark-moderndataengineering#26]
I tried changing the zeppelin image in `docker-compose-all.yaml` to [`apache/zeppelin:0.11.0`](https://hub.docker.com/r/apache/zeppelin/tags) because my Spark version is 3.5.0, but I still got [this error](https://issues.apache.org/jira/browse/ZEPPELIN-5589): 

```
org.apache.zeppelin.interpreter.InterpreterException: java.lang.NoSuchMethodError: scala.tools.nsc.Settings.usejavacp()Lscala/tools/nsc/settings/AbsSettings$AbsSetting;
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.open(LazyOpenInterpreter.java:76)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:833)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:741)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:172)
```

I've given up on Zeppelin for now, but you might want to consider it for a next edition of the book.

**Comment by newfront** [comment]
Let me look into it. Zeppelin as a project seems to be mostly dead at this point too. JupyterLab would be my choice if I had the option to go back in time! hindsight is 20/20.

Let me see if there is a good fix or solution. It is probably a collision in the classpath, Java version, Scala variant, and the internal Java runtime for zeppelin.
